import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@radix-ui/themes/styles.css";
import { Box, Theme } from "@radix-ui/themes";
import "./globals.css";
import AuthProvider from "./auth/Provider";
import ReactQueryProvider from "./ReactQueryProvider";
import NavbarWrapper from "./NavbarWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Theme appearance="light" grayColor="sand">
          <ReactQueryProvider>
            <AuthProvider>
              <main>
                <NavbarWrapper />
                <Box>{children}</Box>
              </main>
            </AuthProvider>
          </ReactQueryProvider>
        </Theme>
      </body>
    </html>
  );
}
